In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-510
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 21 not upgraded.
Need to get 9,599 kB of archives.
After this operation, 29.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 fonts-nanum all 20180306-3 [9,599 kB]
Fetched 9,599 kB in 2s (4,875 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package fonts-nanum.
(Reading database ... 128097 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20180306-3_all.deb ...
Unpacking fonts-nanum (20180306-3) ...
Setting up fonts-nanum (20180306-3) ...
Processing triggers for fontconfig (2.13.1-2ubuntu3) ...
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 10 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [5]:
import pandas as pd
import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler

plt.rc('font', family='NanumBarunGothic')

In [6]:
health = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/국민건강영양조사데이터경진대회/nationalhealth_2010to2021.csv')

In [7]:
health['age'] = health['age'].astype('int')
health

,ID,ID_fam,year,region,town_t,sex,age,incm,ho_incm,incm5,...,고콜레스테롤혈증,고중성지방혈증,B형간염,빈혈,뇌졸중,협심증또는심근경색증,천식,아토피피부염,골관절염,우울증
0,b'A308780901',b'A3087809',2010.0,1.0,1.0,1.0,74,3.0,2.0,4.0,...,0.0,1.0,0.0,0.0,-1.0,-1.0,0.0,-1.0,-1.0,-1.0
1,b'A309099802',b'A3090998',2010.0,1.0,1.0,2.0,71,2.0,1.0,2.0,...,0.0,0.0,0.0,0.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2,b'A309460901',b'A3094609',2010.0,1.0,1.0,2.0,61,3.0,2.0,4.0,...,0.0,0.0,0.0,0.0,-1.0,-1.0,1.0,-1.0,1.0,-1.0
3,b'A309460902',b'A3094609',2010.0,1.0,1.0,1.0,32,2.0,2.0,2.0,...,0.0,1.0,0.0,0.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0
4,b'A310439801',b'A3104398',2010.0,1.0,1.0,2.0,63,4.0,4.0,5.0,...,0.0,0.0,0.0,0.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35624,b'R904322404',b'R9043224',2021.0,8.0,2.0,1.0,53,3.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35625,b'R904332601',b'R9043326',2021.0,8.0,2.0,1.0,50,2.0,2.0,2.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35626,b'R904346201',b'R9043462',2021.0,8.0,2.0,2.0,54,4.0,4.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35627,b'R904353001',b'R9043530',2021.0,8.0,2.0,1.0,45,3.0,3.0,3.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35628,b'R904353002',b'R9043530',2021.0,8.0,2.0,2.0,43,3.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35629 entries, 0 to 35628
Columns: 122 entries, ID to 우울증
dtypes: float64(119), int64(1), object(2)
memory usage: 33.2+ MB

In [9]:
print(health.columns.tolist())

['ID', 'ID_fam', 'year', 'region', 'town_t', 'sex', 'age', 'incm', 'ho_incm', 'incm5', 'ho_incm5', 'edu', 'occp', 'cfam', 'genertn', 'allownc', 'marri_1', 'marri_2', 'fam_rela', 'tins', 'D_1_1', 'educ', 'EC1_1', 'EC_wht_23', 'EC_wht_5', 'EC_pedu_1', 'EC_pedu_2', 'BD1_11', 'BD2_1', 'BD2_31', 'dr_month', 'BP6_10', 'BP7', 'mh_stress', 'BS3_1', 'BE3_31', 'BE5_1', 'LW_mt', 'LW_mt_a1', 'LW_br', 'HE_fst', 'HE_HPdr', 'HE_DMdr', 'HE_mens', 'HE_prg', 'HE_HPfh1', 'HE_HPfh2', 'HE_HPfh3', 'HE_HLfh1', 'HE_HLfh2', 'HE_HLfh3', 'HE_IHDfh1', 'HE_IHDfh2', 'HE_IHDfh3', 'HE_STRfh1', 'HE_STRfh2', 'HE_STRfh3', 'HE_DMfh1', 'HE_DMfh2', 'HE_DMfh3', 'HE_rPLS', 'HE_sbp', 'HE_dbp', 'HE_ht', 'HE_wt', 'HE_wc', 'HE_BMI', 'HE_glu', 'HE_HbA1c', 'HE_chol', 'HE_HDL_st2', 'HE_TG', 'HE_ast', 'HE_alt', 'HE_hepaB', 'HE_HB', 'HE_HCT', 'HE_BUN', 'HE_crea', 'HE_WBC', 'HE_RBC', 'HE_Bplt', 'HE_Uph', 'HE_Unitr', 'HE_Usg', 'HE_Upro', 'HE_Uglu', 'HE_Uket', 'HE_Ubil', 'HE_Ubld', 'HE_Uro', 'HE_Ucrea', 'N_INTK', 'N_EN', 'N_WATER', 'N_PROT', 'N_FAT', 'N_CHO', 'N_CA', 'N_PHOS', 'N_FE', 'N_NA', 'N_K', 'N_CAROT', 'N_RETIN', 'N_B1', 'N_B2', 'N_NIAC', 'N_VITC', '비만', '고혈압', '당뇨병', '고콜레스테롤혈증', '고중성지방혈증', 'B형간염', '빈혈', '뇌졸중', '협심증또는심근경색증', '천식', '아토피피부염', '골관절염', '우울증']

In [10]:
health_info = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/국민건강영양조사데이터경진대회/modified_meta_data20.xlsx',engine='openpyxl')

# 여기까지데이터보기 끝

#csv 전처리

##독거노인 일반사람 not독거노인 csv만들기

전체독거노인

In [11]:
disease = ['비만',
 '고혈압',
 '당뇨병',
 '고콜레스테롤혈증',
 '고중성지방혈증',
 'B형간염',
 '빈혈',
 '뇌졸중',
 '협심증또는심근경색증',
 '천식',
 '아토피피부염',
 '골관절염',
 '우울증']

In [12]:
def dsiease_count(x):
  cnt=0
  for i in disease:
    if x[i] == 1:
      cnt+=1

  return cnt

health['총질병수'] = health.apply(dsiease_count, axis=1) ##총질병수전처리

alone_old_grand = health.query("cfam==1 and fam_rela==1 and age>=65") #65세이상 독거노인
not_alone_old_grand = health.query("cfam!=1 or fam_rela!=1 and age>=65")# 65세이상 독거노인이아닌사람 
young_person = health.query("age<65")

In [13]:
not_alone_old_grand

,ID,ID_fam,year,region,town_t,sex,age,incm,ho_incm,incm5,...,고중성지방혈증,B형간염,빈혈,뇌졸중,협심증또는심근경색증,천식,아토피피부염,골관절염,우울증,총질병수
0,b'A308780901',b'A3087809',2010.0,1.0,1.0,1.0,74,3.0,2.0,4.0,...,1.0,0.0,0.0,-1.0,-1.0,0.0,-1.0,-1.0,-1.0,3
1,b'A309099802',b'A3090998',2010.0,1.0,1.0,2.0,71,2.0,1.0,2.0,...,0.0,0.0,0.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,2
2,b'A309460901',b'A3094609',2010.0,1.0,1.0,2.0,61,3.0,2.0,4.0,...,0.0,0.0,0.0,-1.0,-1.0,1.0,-1.0,1.0,-1.0,5
3,b'A309460902',b'A3094609',2010.0,1.0,1.0,1.0,32,2.0,2.0,2.0,...,1.0,0.0,0.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,4
5,b'A310980901',b'A3109809',2010.0,1.0,1.0,1.0,80,1.0,1.0,2.0,...,0.0,0.0,0.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35624,b'R904322404',b'R9043224',2021.0,8.0,2.0,1.0,53,3.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
35625,b'R904332601',b'R9043326',2021.0,8.0,2.0,1.0,50,2.0,2.0,2.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
35626,b'R904346201',b'R9043462',2021.0,8.0,2.0,2.0,54,4.0,4.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
35627,b'R904353001',b'R9043530',2021.0,8.0,2.0,1.0,45,3.0,3.0,3.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
35628,b'R904353002',b'R9043530',2021.0,8.0,2.0,2.0,43,3.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [14]:
nutritionF = ['N_INTK','N_EN','N_WATER','N_PROT','N_FAT','N_CHO','N_CA','N_PHOS','N_FE','N_NA','N_K','N_CAROT','N_RETIN','N_B1','N_B2','N_NIAC','N_VITC']
nutritionF_name = [
  '식품섭취량',
 '에너지',
 '수분',
 '단백질',
 '지방',
 '탄수화물',
 '칼슘',
 '인',
 '철',
 '나트륨',
 '칼륨',
 '베타카로틴',
 '레티놀',
 '티아민',
 '리보플라빈',
 '나이아신',
 '비타민C']

disease = ['비만',
 '고혈압',
 '당뇨병',
 '고콜레스테롤혈증',
 '고중성지방혈증',
 'B형간염',
 '빈혈',
 '뇌졸중',
 '협심증또는심근경색증',
 '천식',
 '아토피피부염',
 '골관절염',
 '우울증']

# BE부분 운동관련
exercise=[
    'BE3_31',
    'BE5_1'   
] 
#건강검진
health_check = [
'HE_fst',
 'HE_HPdr',
 'HE_DMdr',
 'HE_mens',
 'HE_prg',
 'HE_HPfh1',
 'HE_HPfh2',
 'HE_HPfh3',
 'HE_HLfh1',
 'HE_HLfh2',
 'HE_HLfh3',
 'HE_IHDfh1',
 'HE_IHDfh2',
 'HE_IHDfh3',
 'HE_STRfh1',
 'HE_STRfh2',
 'HE_STRfh3',
 'HE_DMfh1',
 'HE_DMfh2',
 'HE_DMfh3',
 'HE_rPLS',
 'HE_sbp',
 'HE_dbp',
 'HE_ht',
 'HE_wt',
 'HE_wc',
 'HE_BMI',
 'HE_glu',
 'HE_HbA1c',
 'HE_chol',
 'HE_HDL_st2',
 'HE_TG',
 'HE_ast',
 'HE_alt',
 'HE_hepaB',
 'HE_HB',
 'HE_HCT',
 'HE_BUN',
 'HE_crea',
 'HE_WBC',
 'HE_RBC',
 'HE_Bplt',
 'HE_Uph',
 'HE_Unitr',
 'HE_Usg',
 'HE_Upro',
 'HE_Uglu',
 'HE_Uket',
 'HE_Ubil',
 'HE_Ubld',
 'HE_Uro',
 'HE_Ucrea'
]
 
low_nurition = ['N_PROT','N_FAT','N_FE','N_RETIN','N_B1','N_B2','N_NIAC','N_VITC']
low_nurition_name = ['단백질','지방','철','레티놀', '티아민','리보플라빈','나이아신','비타민C']
low_low_nurition = ['N_FE','N_B1','N_B2']
low_low_nurition_name = ['철','티아민','리보플라빈']

##전체 상관분석

In [15]:
health.columns.tolist()

['ID',
 'ID_fam',
 'year',
 'region',
 'town_t',
 'sex',
 'age',
 'incm',
 'ho_incm',
 'incm5',
 'ho_incm5',
 'edu',
 'occp',
 'cfam',
 'genertn',
 'allownc',
 'marri_1',
 'marri_2',
 'fam_rela',
 'tins',
 'D_1_1',
 'educ',
 'EC1_1',
 'EC_wht_23',
 'EC_wht_5',
 'EC_pedu_1',
 'EC_pedu_2',
 'BD1_11',
 'BD2_1',
 'BD2_31',
 'dr_month',
 'BP6_10',
 'BP7',
 'mh_stress',
 'BS3_1',
 'BE3_31',
 'BE5_1',
 'LW_mt',
 'LW_mt_a1',
 'LW_br',
 'HE_fst',
 'HE_HPdr',
 'HE_DMdr',
 'HE_mens',
 'HE_prg',
 'HE_HPfh1',
 'HE_HPfh2',
 'HE_HPfh3',
 'HE_HLfh1',
 'HE_HLfh2',
 'HE_HLfh3',
 'HE_IHDfh1',
 'HE_IHDfh2',
 'HE_IHDfh3',
 'HE_STRfh1',
 'HE_STRfh2',
 'HE_STRfh3',
 'HE_DMfh1',
 'HE_DMfh2',
 'HE_DMfh3',
 'HE_rPLS',
 'HE_sbp',
 'HE_dbp',
 'HE_ht',
 'HE_wt',
 'HE_wc',
 'HE_BMI',
 'HE_glu',
 'HE_HbA1c',
 'HE_chol',
 'HE_HDL_st2',
 'HE_TG',
 'HE_ast',
 'HE_alt',
 'HE_hepaB',
 'HE_HB',
 'HE_HCT',
 'HE_BUN',
 'HE_crea',
 'HE_WBC',
 'HE_RBC',
 'HE_Bplt',
 'HE_Uph',
 'HE_Unitr',
 'HE_Usg',
 'HE_Upro',
 'HE_Uglu',
 'HE_Uket',
 'HE_Ubil',
 'HE_Ubld',
 'HE_Uro',
 'HE_Ucrea',
 'N_INTK',
 'N_EN',
 'N_WATER',
 'N_PROT',
 'N_FAT',
 'N_CHO',
 'N_CA',
 'N_PHOS',
 'N_FE',
 'N_NA',
 'N_K',
 'N_CAROT',
 'N_RETIN',
 'N_B1',
 'N_B2',
 'N_NIAC',
 'N_VITC',
 '비만',
 '고혈압',
 '당뇨병',
 '고콜레스테롤혈증',
 '고중성지방혈증',
 'B형간염',
 '빈혈',
 '뇌졸중',
 '협심증또는심근경색증',
 '천식',
 '아토피피부염',
 '골관절염',
 '우울증',
 '총질병수']

In [16]:
health_info.iloc[10:30]

,Unnamed: 0,variable,variable description,option description,etc,data type,not applicable,unknown,variable bins,selected
10,10,ho_incm5,소득 5분위수(가구),1 : 하 | 2 : 중하 | 3 : 중 | 4 : 중상 | 5 : 상 |,[],category,NaN,NaN,NaN,1
11,11,edu,교육수준 재분류 코드,1 : 초졸이하 | 2 : 중졸 | 3 : 고졸 | 4 : 대졸이상 |,[],category,NaN,NaN,NaN,1
12,12,occp,직업재분류 및 실업/비경제활동 상태 코드,"1 : 관리자, 전문가 및 관련 종사자 | 2 : 사무종사자 | 3 : 서비스 및 ...",[],category,NaN,NaN,NaN,1
13,13,cfam,가구원수,1 : 1명 | 2 : 2명 | 3 : 3명 | 4 : 4명 | 5 : 5명 | 6...,[],category,NaN,9,NaN,1
14,14,genertn,가구 세대구성코드,1 : 1세대 가구 - 1인가구 | 2 : 1세대 가구 - 부부 | 3 : 1세대 ...,[],category,NaN,9,NaN,1
15,15,allownc,기초생활수급 여부,10 : 수급경험 있음(과거 또는 현재) | 20 : 수급경험 없음 | 99 : 모...,[],category,NaN,99,NaN,1
16,16,marri_1,결혼여부,"1 : 기혼 | 2 : 미혼 | 9 : 모름, 무응답 |",[],category,NaN,9,NaN,1
17,17,marri_2,결혼상태,"1 : 유배우자, 동거 | 2 : 유배우자, 별거 | 3 : 사별 | 4 : 이...",[],category,88.0,"8,9,99",NaN,1
18,18,fam_rela,가구주와의 관계,1 : 본인 | 2 : 배우자 | 3 : 자녀 | 4 : 자녀배우자 | 5 : 손자...,[],category,NaN,99,NaN,1
19,19,tins,건강보험종류,10 : 국민건강보험(지역) | 20 : 국민건강보험(직장) | 30 : 의료급여 ...,[],category,NaN,99,NaN,1
20,20,D_1_1,주관적 건강인지,1 : 매우 좋음 | 2 : 좋음 | 3 : 보통 | 4 : 나쁨 | 5 : 매우 ...,[],category,NaN,9,NaN,1
21,21,educ,교육수준: 학력,1 : 서당/한학 | 2 : 무학 | 3 : 초등학교 | 4 : 중학교 | 5 :...,[],category,88.0,99,NaN,1
22,22,EC1_1,경제활동 상태,"1 : 예(취업자) | 2 : 아니오(실업자, 비경제활동인구) | 8 : 비해당(만...",[],category,8.0,9,NaN,1
23,23,EC_wht_23,주당 평균 근로시간,"888 : 비해당(최근 1년 동안 일을 하지 않음) | 999 : 모름, 무응답 |",['□□□시간'],numeric,888.0,999,25.0:40.0:48.0,1
24,24,EC_wht_5,변형근로시간,1 : 주간 근무 | 2 : 저녁 근무(pm14:00~24:00) | 3 : 밤 근...,[],category,88.0,99,NaN,1
25,25,EC_pedu_1,(성인) 유년기환경: 아버지 교육수준,1 : 무학 | 2 : 서당/한학 | 3 : 초등학교 졸업 이하 | 4 : 중학교 ...,[],category,88.0,99,NaN,1
26,26,EC_pedu_2,(성인) 유년기환경: 어머니 교육수준,1 : 무학 | 2 : 서당/한학 | 3 : 초등학교 졸업 이하 | 4 : 중학교 ...,[],category,88.0,99,NaN,1
27,27,BD1_11,(만12세이상) 1년간 음주빈도,1 : 최근 1년간 전혀 마시지 않았다 | 2 : 월1회미만 | 3 : 월1회정도 ...,[],category,8.0,9,NaN,1
28,28,BD2_1,(만12세이상) 한 번에 마시는 음주량,1 : 1-2잔 | 2 : 3-4잔 | 3 : 5-6잔 | 4 : 7-9잔 | 5...,[],category,8.0,9,NaN,1
29,29,BD2_31,(만12세이상) 폭음 빈도,1 : 전혀 없음 | 2 : 월1회미만 | 3 : 월1회정도 | 4 : 주1회정도 ...,[],category,8.0,9,NaN,1

In [17]:
all_mean_columns = ['town_t',
 'sex',
 'age',
 'incm',
 'ho_incm',
 'incm5',
 'ho_incm5',
 'edu',
 'occp',
 'cfam',
 'genertn',
 'allownc',
 'marri_1',
 'marri_2',
 'fam_rela',
 'tins',
 'D_1_1',
 'educ',
 'EC1_1',
 'EC_wht_23',
 'EC_wht_5',
 'EC_pedu_1',
 'EC_pedu_2',
 'BD1_11',
 'BD2_1',
 'BD2_31',
 'dr_month',
 'BP6_10',
 'BP7',
 'mh_stress',
 'BS3_1',
 'BE3_31',
 'BE5_1',
 'LW_mt',
 'LW_mt_a1',
 'LW_br',
 'HE_fst',
 'HE_HPdr',
 'HE_DMdr',
 'HE_mens',
 'HE_prg',
 'HE_HPfh1',
 'HE_HPfh2',
 'HE_HPfh3',
 'HE_HLfh1',
 'HE_HLfh2',
 'HE_HLfh3',
 'HE_IHDfh1',
 'HE_IHDfh2',
 'HE_IHDfh3',
 'HE_STRfh1',
 'HE_STRfh2',
 'HE_STRfh3',
 'HE_DMfh1',
 'HE_DMfh2',
 'HE_DMfh3',
 'HE_rPLS',
 'HE_sbp',
 'HE_dbp',
 'HE_ht',
 'HE_wt',
 'HE_wc',
 'HE_BMI',
 'HE_glu',
 'HE_HbA1c',
 'HE_chol',
 'HE_HDL_st2',
 'HE_TG',
 'HE_ast',
 'HE_alt',
 'HE_hepaB',
 'HE_HB',
 'HE_HCT',
 'HE_BUN',
 'HE_crea',
 'HE_WBC',
 'HE_RBC',
 'HE_Bplt',
 'HE_Uph',
 'HE_Unitr',
 'HE_Usg',
 'HE_Upro',
 'HE_Uglu',
 'HE_Uket',
 'HE_Ubil',
 'HE_Ubld',
 'HE_Uro',
 'HE_Ucrea',
 'N_INTK',
 'N_EN',
 'N_WATER',
 'N_PROT',
 'N_FAT',
 'N_CHO',
 'N_CA',
 'N_PHOS',
 'N_FE',
 'N_NA',
 'N_K',
 'N_CAROT',
 'N_RETIN',
 'N_B1',
 'N_B2',
 'N_NIAC',
 'N_VITC',
 '비만',
 '고혈압',
 '당뇨병',
 '고콜레스테롤혈증',
 '고중성지방혈증',
 'B형간염',
 '빈혈',
 '뇌졸중',
 '협심증또는심근경색증',
 '천식',
 '아토피피부염',
 '골관절염',
 '우울증',
 '총질병수']

region_alone_old_grand_name = ['서울','부산','대구','인천','광주','대전','울산','세종','경기','강원','충북','충남','전북','전남','경북','경남','제주']

## 질병에관한 전체상관분석

In [18]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [19]:
sub_col = [x for x in all_mean_columns if x not in disease]

def disease_all_corr(start, end):
  df1 = health[sub_col[start:end]]
  df2 = health[disease]

  df = pd.concat([df1,df2], axis=1)
  scaler = MinMaxScaler()
  scaler.fit(df)
  df_scaled = scaler.transform(df)
  scaled_df = pd.DataFrame(df_scaled,  columns=df.columns)
  corr_df = scaled_df.corr(method='pearson')

  plt.figure(figsize=(35,15))
  sns.heatmap(corr_df, annot=True, fmt=".2f", cmap='Blues')

disease_all_corr(0,20)
disease_all_corr(20,40)
disease_all_corr(40,60)
disease_all_corr(60,80)
disease_all_corr(80,100)
disease_all_corr(100,107)

Output hidden; open in https://colab.research.google.com to view.

## 지역별로 질병 전체상관분석

In [20]:
health['region'].value_counts()

1.0     6714
9.0     5181
8.0     3888
2.0     2182
4.0     1985
15.0    1959
3.0     1784
14.0    1707
16.0    1615
12.0    1379
11.0    1308
10.0    1281
13.0    1209
6.0     1151
5.0     1124
7.0      772
17.0     390
Name: region, dtype: int64

In [21]:
sub_col = [x for x in all_mean_columns if x not in disease]

def disease_region_corr(start, end, region_n):
  region_health = health[health['region']==region_n]
  
  # print(region_health)

  df1 = region_health[sub_col[start:end]]
  df2 = region_health[disease]

  df = pd.concat([df1,df2], axis=1)
  # print(df)
  scaler = MinMaxScaler()
  scaler.fit(df)
  df_scaled = scaler.transform(df)
  scaled_df = pd.DataFrame(df_scaled,  columns=df.columns)
  corr_df = scaled_df.corr(method='pearson')

  _=plt.figure(figsize=(35,15))
  _=plt.title(f"{region_alone_old_grand_name[i-1]}")
  _=sns.heatmap(corr_df, annot=True, fmt=".2f", cmap='Blues')


for i in range(1,18):
  disease_region_corr(0,20,i)
  disease_region_corr(20,40,i)
  disease_region_corr(40,60,i)
  disease_region_corr(60,80,i)
  disease_region_corr(80,100,i)
  disease_region_corr(100,107,i)

# disease_region_corr(0,20,1)

Output hidden; open in https://colab.research.google.com to view.